import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/component/Navbar";
import Footer from "@/component/Footer";
import SessionWrapper from "@/component/SessionWrapper";
import Script from "next/script";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head><meta name="viewport" content="width=device-width, height=device-height, initial-scale=1.0, maximum-scale=1.0" /></head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} font-sans antialiased cursor-default`}
      > <SessionWrapper>
          <Navbar />
          {children}
          <Footer />
          <Script src="https://cdn.lordicon.com/lordicon.js" strategy="afterInteractive" />
          <Script src="https://sdk.cashfree.com/js/v3/cashfree.js" strategy="afterInteractive" />
        </SessionWrapper>
      </body>
    </html>
  );
}
